[package]
name = "problem1878"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1878a"
path = "src/problem1878a.rs"

[[bin]]
name = "p1878b"
path = "src/problem1878b.rs"

[[bin]]
name = "p1878c"
path = "src/problem1878c.rs"
