[package]
name = "problem1454"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1454a"
path = "src/problem1454a.rs"

[[bin]]
name = "p1454b"
path = "src/problem1454b.rs"
