[package]
name = "problem1881"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1881a"
path = "src/problem1881a.rs"

[[bin]]
name = "p1881b"
path = "src/problem1881b.rs"
