[package]
name = "problem1931"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1931a"
path = "src/problem1931a.rs"

[[bin]]
name = "p1931b"
path = "src/problem1931b.rs"

[[bin]]
name = "p1931c"
path = "src/problem1931c.rs"
