[package]
name = "problem1674"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1674a"
path = "src/problem1674a.rs"

[[bin]]
name = "p1674b"
path = "src/problem1674b.rs"
