[package]
name = "problem1985"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1985a"
path = "src/problem1985a.rs"

[[bin]]
name = "p1985b"
path = "src/problem1985b.rs"

[[bin]]
name = "p1985c"
path = "src/problem1985c.rs"

[[bin]]
name = "p1985d"
path = "src/problem1985d.rs"
