[package]
name = "problem1945"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1945a"
path = "src/problem1945a.rs"

[[bin]]
name = "p1945b"
path = "src/problem1945b.rs"
