[package]
name = "problem1547"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1547a"
path = "src/problem1547a.rs"

[[bin]]
name = "p1547b"
path = "src/problem1547b.rs"
