[package]
name = "problem1519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1519a"
path = "src/problem1519a.rs"

[[bin]]
name = "p1519b"
path = "src/problem1519b.rs"
