[package]
name = "problem1359"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1359a"
path = "src/problem1359a.rs"

[[bin]]
name = "p1359b"
path = "src/problem1359b.rs"
