[package]
name = "problem2000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2000a"
path = "src/problem2000a.rs"

[[bin]]
name = "p2000b"
path = "src/problem2000b.rs"
