[package]
name = "problem1206"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1206a"
path = "src/problem1206a.rs"

[[bin]]
name = "p1206b"
path = "src/problem1206b.rs"
