[package]
name = "problem1883"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1883a"
path = "src/problem1883a.rs"

[[bin]]
name = "p1883b"
path = "src/problem1883b.rs"

[[bin]]
name = "p1883c"
path = "src/problem1883c.rs"
