[package]
name = "problem1968"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1968a"
path = "src/problem1968a.rs"

[[bin]]
name = "p1968b"
path = "src/problem1968b.rs"

[[bin]]
name = "p1968c"
path = "src/problem1968c.rs"
