[package]
name = "problem1703"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p1703c"
path = "src/problem1703c.rs"

[[bin]]
name = "p1703d"
path = "src/problem1703d.rs"

[[bin]]
name = "p1703e"
path = "src/problem1703e.rs"
