[package]
name = "problem1881"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p1881a"
path = "src/problem1881a.rs"

[[bin]]
name = "p1881b"
path = "src/problem1881b.rs"

[[bin]]
name = "p1881d"
path = "src/problem1881d.rs"
