[package]
name = "problem1840"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1840a"
path = "src/problem1840a.rs"

[[bin]]
name = "p1840c"
path = "src/problem1840c.rs"
