[package]
name = "problem1633"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1633a"
path = "src/problem1633a.rs"

[[bin]]
name = "p1633b"
path = "src/problem1633b.rs"
