[package]
name = "problem1497"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1497a"
path = "src/problem1497a.rs"

[[bin]]
name = "p1497c1"
path = "src/problem1497c1.rs"
