[package]
name = "problem1692"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p1692b"
path = "src/problem1692b.rs"

[[bin]]
name = "p1692c"
path = "src/problem1692c.rs"

[[bin]]
name = "p1692f"
path = "src/problem1692f.rs"
