[package]
name = "problem0479"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0479a"
path = "src/problem0479a.rs"

[[bin]]
name = "p0479c"
path = "src/problem0479c.rs"
