[package]
name = "problem1971"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1971a"
path = "src/problem1971a.rs"

[[bin]]
name = "p1971b"
path = "src/problem1971b.rs"

[[bin]]
name = "p1971c"
path = "src/problem1971c.rs"

[[bin]]
name = "p1971d"
path = "src/problem1971d.rs"
