[package]
name = "problem2091"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p2091a"
path = "src/problem2091a.rs"

[[bin]]
name = "p2091b"
path = "src/problem2091b.rs"

[[bin]]
name = "p2091c"
path = "src/problem2091c.rs"
