[package]
name = "problem1941"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1941a"
path = "src/problem1941a.rs"

[[bin]]
name = "p1941b"
path = "src/problem1941b.rs"

[[bin]]
name = "p1941c"
path = "src/problem1941c.rs"
