[package]
name = "problem1846"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1846a"
path = "src/problem1846a.rs"

[[bin]]
name = "p1846b"
path = "src/problem1846b.rs"
