[package]
name = "problem1676"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1676c"
path = "src/problem1676c.rs"

[[bin]]
name = "p1676e"
path = "src/problem1676e.rs"
