[package]
name = "problem1660"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1660a"
path = "src/problem1660a.rs"

[[bin]]
name = "p1660b"
path = "src/problem1660b.rs"
