[package]
name = "problem1955"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1955a"
path = "src/problem1955a.rs"

[[bin]]
name = "p1955b"
path = "src/problem1955b.rs"
