[package]
name = "problem0734"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0734a"
path = "src/problem0734a.rs"

[[bin]]
name = "p0734b"
path = "src/problem0734b.rs"
