[package]
name = "problem2035"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2035a"
path = "src/problem2035a.rs"

[[bin]]
name = "p2035b"
path = "src/problem2035b.rs"
