[package]
name = "problem2007"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2007a"
path = "src/problem2007a.rs"

[[bin]]
name = "p2007b"
path = "src/problem2007b.rs"
