[package]
name = "problem1856"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1856a"
path = "src/problem1856a.rs"

[[bin]]
name = "p1856b"
path = "src/problem1856b.rs"
