[package]
name = "problem0450"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0450a"
path = "src/problem0450a.rs"

[[bin]]
name = "p0450b"
path = "src/problem0450b.rs"
