[package]
name = "problem1607"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1607b"
path = "src/problem1607b.rs"

[[bin]]
name = "p1607c"
path = "src/problem1607c.rs"
