[package]
name = "problem1772"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1772a"
path = "src/problem1772a.rs"

[[bin]]
name = "p1772b"
path = "src/problem1772b.rs"
