[package]
name = "problem1927"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1927a"
path = "src/problem1927a.rs"

[[bin]]
name = "p1927b"
path = "src/problem1927b.rs"

[[bin]]
name = "p1927c"
path = "src/problem1927c.rs"
