[package]
name = "problem1858"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1858a"
path = "src/problem1858a.rs"

[[bin]]
name = "p1858c"
path = "src/problem1858c.rs"
