[package]
name = "problem1862"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1862a"
path = "src/problem1862a.rs"

[[bin]]
name = "p1862b"
path = "src/problem1862b.rs"
