[package]
name = "problem1744"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1744a"
path = "src/problem1744a.rs"

[[bin]]
name = "p1744b"
path = "src/problem1744b.rs"
