[package]
name = "problem1855"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1855a"
path = "src/problem1855a.rs"

[[bin]]
name = "p1855b"
path = "src/problem1855b.rs"
