[package]
name = "problem2003"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2003a"
path = "src/problem2003a.rs"

[[bin]]
name = "p2003b"
path = "src/problem2003b.rs"
