[package]
name = "problem1956"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1956a"
path = "src/problem1956a.rs"

[[bin]]
name = "p1956b"
path = "src/problem1956b.rs"
