[package]
name = "problem2010"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2010a"
path = "src/problem2010a.rs"

[[bin]]
name = "p2010b"
path = "src/problem2010b.rs"
