[package]
name = "problem1462"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1462b"
path = "src/problem1462b.rs"

[[bin]]
name = "p1462c"
path = "src/problem1462c.rs"
