[package]
name = "problem2033"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2033a"
path = "src/problem2033a.rs"

[[bin]]
name = "p2033b"
path = "src/problem2033b.rs"
