[package]
name = "problem1859"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1859a"
path = "src/problem1859a.rs"

[[bin]]
name = "p1859b"
path = "src/problem1859b.rs"
