[package]
name = "problem2008"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2008a"
path = "src/problem2008a.rs"

[[bin]]
name = "p2008b"
path = "src/problem2008b.rs"

[[bin]]
name = "p2008c"
path = "src/problem2008c.rs"
