[package]
name = "problem2038"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2038j"
path = "src/problem2038j.rs"

[[bin]]
name = "p2038n"
path = "src/problem2038n.rs"
