[package]
name = "problem0268"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0268a"
path = "src/problem0268a.rs"

[[bin]]
name = "p0268b"
path = "src/problem0268b.rs"
