[package]
name = "problem0276"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0276a"
path = "src/problem0276a.rs"

[[bin]]
name = "p0276b"
path = "src/problem0276b.rs"
