[package]
name = "problem2036"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2036a"
path = "src/problem2036a.rs"

[[bin]]
name = "p2036b"
path = "src/problem2036b.rs"
