[package]
name = "problem1837"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1837a"
path = "src/problem1837a.rs"

[[bin]]
name = "p1837b"
path = "src/problem1837b.rs"
