[package]
name = "problem1933"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "p1933a"
path = "src/problem1933a.rs"

[[bin]]
name = "p1933b"
path = "src/problem1933b.rs"
