[package]
name = "problem1326"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1326a"
path = "src/problem1326a.rs"

[[bin]]
name = "p1326b"
path = "src/problem1326b.rs"
