[package]
name = "problem1791"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1791d"
path = "src/problem1791d.rs"

[[bin]]
name = "p1791e"
path = "src/problem1791e.rs"
