[package]
name = "problem1703"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1703c"
path = "src/problem1703c.rs"

[[bin]]
name = "p1703d"
path = "src/problem1703d.rs"
