[package]
name = "problem2013"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2013a"
path = "src/problem2013a.rs"

[[bin]]
name = "p2013b"
path = "src/problem2013b.rs"
