[package]
name = "problem0766"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0766a"
path = "src/problem0766a.rs"

[[bin]]
name = "p0766b"
path = "src/problem0766b.rs"
