[package]
name = "problem2009"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p2009a"
path = "src/problem2009a.rs"

[[bin]]
name = "p2009b"
path = "src/problem2009b.rs"

[[bin]]
name = "p2009c"
path = "src/problem2009c.rs"
