[package]
name = "problem1373"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1373a"
path = "src/problem1373a.rs"

[[bin]]
name = "p1373b"
path = "src/problem1373b.rs"
