[package]
name = "problem1541"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1541a"
path = "src/problem1541a.rs"

[[bin]]
name = "p1541b"
path = "src/problem1541b.rs"
