[package]
name = "problem1339"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1339a"
path = "src/problem1339a.rs"

[[bin]]
name = "p1339b"
path = "src/problem1339b.rs"
