[package]
name = "problem1697"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1697a"
path = "src/problem1697a.rs"

[[bin]]
name = "p1697b"
path = "src/problem1697b.rs"
