[package]
name = "problem1345"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1345a"
path = "src/problem1345a.rs"

[[bin]]
name = "p1345b"
path = "src/problem1345b.rs"
