[package]
name = "problem1921"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1921a"
path = "src/problem1921a.rs"

[[bin]]
name = "p1921b"
path = "src/problem1921b.rs"

[[bin]]
name = "p1921c"
path = "src/problem1921c.rs"
