[package]
name = "problem1213"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1213a"
path = "src/problem1213a.rs"

[[bin]]
name = "p1213b"
path = "src/problem1213b.rs"
