[package]
name = "problem1988"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1988a"
path = "src/problem1988a.rs"

[[bin]]
name = "p1988b"
path = "src/problem1988b.rs"
