[package]
name = "problem0978"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p0978a"
path = "src/problem0978a.rs"

[[bin]]
name = "p0978c"
path = "src/problem0978c.rs"
