[package]
name = "problem2037"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p2037a"
path = "src/problem2037a.rs"

[[bin]]
name = "p2037b"
path = "src/problem2037b.rs"
