[package]
name = "problem1950"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1950a"
path = "src/problem1950a.rs"

[[bin]]
name = "p1950b"
path = "src/problem1950b.rs"

[[bin]]
name = "p1950c"
path = "src/problem1950c.rs"
