[package]
name = "problem1611"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1611a"
path = "src/problem1611a.rs"

[[bin]]
name = "p1611b"
path = "src/problem1611b.rs"
