[package]
name = "problem1999"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1999a"
path = "src/problem1999a.rs"

[[bin]]
name = "p1999b"
path = "src/problem1999b.rs"

[[bin]]
name = "p1999c"
path = "src/problem1999c.rs"

[[bin]]
name = "p1999d"
path = "src/problem1999d.rs"
