[package]
name = "problem1974"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1974a"
path = "src/problem1974a.rs"

[[bin]]
name = "p1974b"
path = "src/problem1974b.rs"
