[package]
name = "problem1807"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "b"
path = "src/problem1807b.rs"

[[bin]]
name = "c"
path = "src/problem1807c.rs"