[package]
name = "problem1986"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "p1986a"
path = "src/problem1986a.rs"

[[bin]]
name = "p1986b"
path = "src/problem1986b.rs"
